# @file rockylinux9.yml
---
name: Tests on Rocky Linux 9

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  help:
    name: Launch plugin with --help
    runs-on: ubuntu-latest
    container: 
      image: rockylinux/rockylinux:9
    steps:
    - uses: actions/checkout@v1
    - name: Enable EPEL
      run: |
        dnf install -y dnf-plugins-core
        dnf config-manager --set-enabled crb
        dnf install -y epel-release
    - name: Install dependencies
      run: |
        dnf -y install nagios-plugins-perl perl-FindBin perl-lib
    - name: Move Plugin to nagios-plugins dir
      run: |
        mv check_ro_mounts.pl /usr/lib64/nagios/plugins/
    - name: Launch plugin with --help
      run: |
        /usr/lib64/nagios/plugins/check_ro_mounts.pl --help
  execute:
    runs-on: ubuntu-latest
    container: 
      image: rockylinux/rockylinux:9
    steps:
    - uses: actions/checkout@v1
    - name: Enable EPEL
      run: |
        dnf install -y dnf-plugins-core
        dnf config-manager --set-enabled crb
        dnf install -y epel-release
    - name: Install dependencies
      run: |
        dnf -y install nagios-plugins-perl perl-FindBin perl-lib
    - name: Move Plugin to nagios-plugins dir
      run: |
        mv check_ro_mounts.pl /usr/lib64/nagios/plugins/
    - name: Launch plugin
      run: |
        /usr/lib64/nagios/plugins/check_ro_mounts.pl -d
